# Generated by Django 6.0.3 on 2026-04-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaitem',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
